#!/bin/sh
##SBATCH --time=08:00:00
#SBATCH --signal=USR2
#SBATCH --ntasks=1
##SBATCH --cpus-per-task=2
##SBATCH --mem=8192
##SBATCH --output=/home/%u/rstudio-server.job.%j
# customize --output path as appropriate (to a directory readable only by the user!)

if [ "$1" = "" ] ; then V="4.2.2" ; else V=$1 ; fi 

RSTUDIO_IMAGE="rstudio_${V}.sif" 
RSTUDIO_VERSION=$(echo ${V} | awk -F. '{ print $1"."$2 }')

# Create temporary directory to be populated with directories to bind-mount in the container
# where writable file systems are necessary. Adjust path as appropriate for your computing environment.
mkdir -p ~/.rstudio-age/tmp
workdir=$(python3 -c 'import tempfile; import os; HOME=os.getenv("HOME") ; print(tempfile.mkdtemp(prefix=f"{HOME}/.rstudio-age/tmp/"))')

mkdir -p -m 700 ${workdir}/run ${workdir}/tmp ${workdir}/var/lib/rstudio-server
cat > ${workdir}/database.conf <<END
provider=sqlite
directory=/var/lib/rstudio-server
END

# Set OMP_NUM_THREADS to prevent OpenBLAS (and any other OpenMP-enhanced
# libraries used by R) from spawning more threads than the number of processors
# allocated to the job.
#
# Set R_LIBS_USER to a path specific to rocker/rstudio to avoid conflicts with
# personal libraries from any R installation in the host environment

if [ "${SLURM_JOB_CPUS_PER_NODE}" = "" ] ; then SLURM_JOB_CPUS_PER_NODE=2 ; fi

cat > ${workdir}/rsession.sh <<END
#!/bin/sh
export OMP_NUM_THREADS=${SLURM_JOB_CPUS_PER_NODE}
export R_LIBS_USER=${HOME}/.rstudio-age/rocker-rstudio/${RSTUDIO_VERSION}
mkdir -p ${HOME}/.rstudio-age/rocker-rstudio/${RSTUDIO_VERSION}
exec /usr/lib/rstudio-server/bin/rsession "\${@}"
END

chmod +x ${workdir}/rsession.sh

export APPTAINER_BIND="${workdir}/run:/run,${workdir}/tmp:/tmp,${workdir}/database.conf:/etc/rstudio/database.conf,${workdir}/rsession.sh:/etc/rstudio/rsession.sh,${workdir}/var/lib/rstudio-server:/var/lib/rstudio-server"

# Do not suspend idle sessions.
# Alternative to setting session-timeout-minutes=0 in /etc/rstudio/rsession.conf
# https://github.com/rstudio/rstudio/blob/v1.4.1106/src/cpp/server/ServerSessionManager.cpp#L126
# export SINGULARITYENV_RSTUDIO_SESSION_TIMEOUT=0

export APPTAINERENV_USER=$(id -un) 
export APPTAINERENV_PASSWORD=$(openssl rand -base64 15)

# export SINGULARITYENV_USER=$(id -un) 
# export SINGULARITYENV_PASSWORD=$(openssl rand -base64 15)

# get unused socket per https://unix.stackexchange.com/a/132524
# tiny race condition between the python & singularity commands
readonly PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

HOSTNAME=$(hostnamectl | grep hostname | awk '{ print $3}')

cat 1>&2 <<END

ATTENTION: RStudio Server Community Edition only provides unencrypted HTTP access.

1. point your web browser to http://${HOSTNAME}.age.mpg.de:${PORT}

2. log in to RStudio Server using the following credentials:

   user: ${APPTAINERENV_USER}
   password: ${APPTAINERENV_PASSWORD}

When done using RStudio Server, terminate the job by:

1. Exit the RStudio Session ("power" button in the top right corner of the RStudio window)
END

if [ "${SLURM_JOB_ID}" = "" ] ; then
cat 1>&2 <<END   
      
END
else
cat 1>&2 <<END

2. Issue the following command on the login node:

      scancel -f ${SLURM_JOB_ID}
      
END
fi

# cat 1>&2 <<END
# 1. SSH tunnel from your workstation using the following command:

#    ssh -N -L 8787:${HOSTNAME}:${PORT} ${SINGULARITYENV_USER}@LOGIN-HOST

#    and point your web browser to http://localhost:8787

# 2. log in to RStudio Server using the following credentials:

#    user: ${APPTAINERENV_USER}
#    password: ${APPTAINERENV_PASSWORD}

# When done using RStudio Server, terminate the job by:

# 1. Exit the RStudio Session ("power" button in the top right corner of the RStudio window)
# 2. Issue the following command on the login node:

#       scancel -f ${SLURM_JOB_ID}
      
# END

singularity exec --cleanenv /beegfs/common/singularity/rstudio/${RSTUDIO_IMAGE} \
    /usr/lib/rstudio-server/bin/rserver --www-port ${PORT} \
            --auth-none=0 \
            --auth-pam-helper-path=pam-helper \
            --auth-stay-signed-in-days=30 \
            --auth-timeout-minutes=0 \
            --rsession-path=/etc/rstudio/rsession.sh \
            --server-user=${USER}
printf 'rserver exited' 1>&2