#!/bin/sh
#SBATCH --time=08:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8192
#SBATCH --output=posit-jupyter.job.%j

POSIT_JUPYTER_IMAGE="/nexus/posix0/MAGE-flaski/service/images/posit-latest.sif"

# Create directory to be populated with directories to bind-mount in the container
# where writable file systems are necessary. Adjust path as appropriate for your computing environment.
workdir=$(eval echo ~/.posit-jupyter-age)
mkdir -p $workdir
mkdir -p -m 700 $workdir/tmp $workdir/run

export APPTAINER_BIND="${workdir}/run:/run,${workdir}/tmp:/tmp"

export APPTAINERENV_USER=$(id -un) 
export JUPYTER_LABTOKEN=$(openssl rand -base64 15)

# get unused socket per https://unix.stackexchange.com/a/132524
# tiny race condition between the python & singularity commands
readonly PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

NODEIP=$(hostname -I | grep -Eo '192\.168\.42\.[0-9]+')

cat 1>&2 <<END

ATTENTION: Posit Jupyter only provides unencrypted HTTP access.

1. Run from local computer: ssh -N -L 8788:${NODEIP}:${PORT} -J ${APPTAINERENV_USER}@raven.mpcdf.mpg.de ${APPTAINERENV_USER}@hpc.bioinformatics.studio
   and point your web browser to http://127.0.0.1:8788/lab?token=${JUPYTER_LABTOKEN}

When done using Jupyter Lab, terminate the job by:

1. End the ssh port tunneling from the local computer terminal
END

if [ "${SLURM_JOB_ID}" = "" ] ; then
cat 1>&2 <<END   
      
END
else
cat 1>&2 <<END

2. Issue the following command on the login node:

      scancel -f ${SLURM_JOB_ID}
      
END
fi

singularity exec --cleanenv ${POSIT_JUPYTER_IMAGE} \
    jupyter lab --no-browser \
        --ip=0.0.0.0 \
        --NotebookApp.token=${JUPYTER_LABTOKEN} \
        --port=${PORT} >/dev/null 2>&1

printf 'rserver exited' 1>&2