#!/bin/sh
#SBATCH --time=08:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8192
#SBATCH --output=vscode.job.%j

# Set image 
# docker image from: https://hub.docker.com/_/microsoft-vscode-devcontainers
VSCODE_IMAGE="/nexus/posix0/MAGE-flaski/service/images/vscode_ubuntu.sif"

# In order to use a different image provided with 'sbatch --export=ALL,IMAGE=<image_path>'
[ -n "$IMAGE" ] && VSCODE_IMAGE="$IMAGE"

# In order to use a different image provided with '<script> -i <image_path>'
while getopts "i:" opt; do
    case $opt in
        i) VSCODE_IMAGE="$OPTARG" ;;
        *) exit 1 ;;
    esac
done

# Create temporary directory to be populated with directories to bind-mount in the container
# where writable file systems are necessary. Adjust path as appropriate for your computing environment.
workdir=$(eval echo ~/.vscode-age)
mkdir -p $workdir
mkdir -p -m 700 $workdir/tmp $workdir/run $workdir/ssl

# Generate self assigned ssl keys for secure https connection
if ! openssl x509 -in "$workdir/ssl/vscode.crt" -noout -enddate 2>/dev/null | grep -q "notAfter"; then
    rm $workdir/ssl/* 2>/dev/null
    openssl req -x509 -out $workdir/ssl/vscode.crt -keyout $workdir/ssl/vscode.key \
        -newkey rsa:2048 -nodes -days 365 -sha256 \
        -subj '/CN=localhost' 2>/dev/null
fi

export APPTAINER_BIND="${workdir}/run:/run,${workdir}/tmp:/tmp"

export APPTAINERENV_USER=$(id -un) 
export APPTAINERENV_VSPASSWORD=$(openssl rand -base64 15)

# get unused socket per https://unix.stackexchange.com/a/132524
# tiny race condition between the python & singularity commands
readonly PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

cat > ${workdir}/config.yaml <<END
bind-addr: 0.0.0.0:${PORT}
auth: password
password: ${APPTAINERENV_VSPASSWORD}
cert: $workdir/ssl/vscode.crt
cert-key: $workdir/ssl/vscode.key
END

NODEIP=$(hostname -I | grep -Eo '192\.168\.42\.[0-9]+')

cat 1>&2 <<END

ATTENTION: VS Code provides encrypted HTTPS access.

1. Run from local computer: ssh -N -L 8080:${NODEIP}:${PORT} ${APPTAINERENV_USER}@hpc.bioinformatics.studio
   and point your web browser to https://127.0.0.1:8080

   *** Please avoid the browser message of [not secure] and advance to open the page. The connection is encrypted and secured with ssl self-signed key.

2. log in to VS Code using the following credentials:

   password: ${APPTAINERENV_VSPASSWORD}

When done using VS Code, terminate the job by:

1. End the ssh port tunneling from the local computer terminal
END

if [ "${SLURM_JOB_ID}" = "" ] ; then
cat 1>&2 <<END   
      
END
else
cat 1>&2 <<END

2. Issue the following command on the login node:

      scancel -f ${SLURM_JOB_ID}
      
END
fi

singularity exec --cleanenv ${VSCODE_IMAGE} \
    code-server --disable-update-check \
        --config=${workdir}/config.yaml \
        --welcome-text="Get the password from the job output!" >/dev/null 2>&1

printf 'vs code exited' 1>&2